name: Build and deploy header file

on:
  workflow_run:
    workflows: [ Validate ]
    branches: [ "main" ]
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - run: ls -l
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Checkout lib repository
        uses: actions/checkout@v4
        with:
          repository: PavelProjects/SmartThingLib
          path: ./SmartThingLib
          ref: develop
      - name: Build header
        run: npm run deploy-header --dest="$(pwd)/SmartThingLib"
      - name: Commit and push changes
        run: |
          cd ./SmartThingLib
          git config --global user.email "<>"
          git config --global user.name "$USERNAME"
          git add -A
          git commit -m "Auto web update - ${{ github.event.workflow_run.head_commit.message }}"
          git push "https://PavelProjects:$LIB_REPO_TOKEN@github.com/PavelProjects/SmartThingLib.git"
        env:
          LIB_REPO_TOKEN: ${{ secrets.LIB_REPO_TOKEN }}
          USERNAME: GuthubActions[bot]
